version: '2'

services:
  namenode:
    image: pocketcluster/amd64-jupyter-master-4.2.1:dev
#    pid: "host"
    container_name: pc-core
    hostname: pc-core
    ports:
      - "8080:8080"
      - "8888:8888"
    networks:
      hadoop:
        ipv4_address: 172.16.128.1
    volumes:
      - /pocket/hadoop/2.7.3:/pocket/hadoop
      - /pocket/spark/2.1.0:/pocket/spark
      - /pocket/workspace:/pocket/workspace
    environment:
      - CLUSTER_NAME=pocketcluster/hadoop-spark-note
      - SLAVE_NODES=pc-node1=172.16.128.2;pc-node2=172.16.128.3
      - constraint:node==pc-core
    depends_on:
      - datanode1
      - datanode2
      
  datanode1:
    image: pocketcluster/armhf-jupyter-slave-4.2.1:dev
    container_name: pc-node1
    hostname: pc-node1
    networks:
      hadoop:
        ipv4_address: 172.16.128.2
    volumes:
      - /pocket/hadoop/2.7.3:/pocket/hadoop
      - /pocket/spark/2.1.0:/pocket/spark
    environment:
      - constraint:node==pocket

  datanode2:
    image: pocketcluster/armhf-jupyter-slave-4.2.1:dev
    container_name: pc-node2
    hostname: pc-node2
    networks:
      hadoop:
        ipv4_address: 172.16.128.3
    volumes:
      - /pocket/hadoop/2.7.3:/pocket/hadoop
      - /pocket/spark/2.1.0:/pocket/spark
    environment:
      - constraint:node==pocket-node

networks:
  hadoop:
    driver: overlay
    ipam:
      config:
        - subnet: 172.16.128.0/24
          gateway: 172.16.128.254
          ip_range: 172.16.128.0/24
