# --- APACHE SPARK 2.1.0 ENV ---

#export SCALA_PATH="$(type -p scala)"
#SCALA_HOME=""
#if [[ -n $SCALA_PATH ]] && [[ -x $SCALA_PATH ]]; 
#then
#	export SCALA_HOME=${SCALA_PATH/scala/}
#fi

export SPARK_HOME=/opt/spark
export SPARK_CONF_DIR=/etc/spark
export PATH=$PATH:$SPARK_HOME/bin
