FROM pocketcluster/amd64-hadoop-base-2.6.5:BUILDCHAINTAG
MAINTAINER PocketCluster <stkim1@pocketcluster.io>

# ROOT USER
USER root

# Enable SSHD
RUN rm -f /etc/service/sshd/down

# Prepare files
COPY hadoop-launch.sh /etc/my_init.d/01_launch_hadoop
RUN chmod a+x /etc/my_init.d/01_launch_hadoop

CMD ["/sbin/my_init"]

EXPOSE 22 7373 7946 8030 8031 8032 8033 8040 8042 8060 8088 9000 10020 19888 50010 50020 50060 50070 50075 50090 50475 54310 54311